site_name: "IoT con AI - Documentación"
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: dark-amber
      toggle:
        icon: material/weather-night
        name: "Cambiar a modo oscuro"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/white-balance-sunny
        name: "Cambiar a modo claro"
  font:
    text: "Poppins"
    code: "Fira Code"

  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - content.code.annotate
    - search.suggest
    - search.highlight
    - toc.follow
    - content.action.edit

nav:
  - Inicio: index.md
  - Fases del Proyecto:
      - Diseño de Circuitos: fase1.md
      - Desarrollo Web IoT: fase2.md
      - Implementación de AI: fase3.md
  - Recursos: recursos.md
  - Sobre el Proyecto: about.md

extra:
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico

extra_css:
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - assets/styles/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.magiclink

  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.2.3/mermaid.min.js
  - assets/scripts/init-mermaid.js
  - assets/scripts/main.js

repo_url: https://github.com/MDMSerra/iot-ai-project-docs
edit_uri: edit/main/docs/
